**PREPROCESSING**

In [245]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from scipy.stats import chi2_contingency
from scipy.stats import f_oneway
from imblearn.over_sampling import SMOTE

from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import TargetEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [246]:
df = pd.read_csv("C:\\Users\\Abhishek k\\OneDrive\\Documents\\projects\\mini project ml\\Dataset\\dataset_final22.csv")

In [247]:
df.tail()

,Key Id,Tournament Id,tournament Name,Match Id,Match Name,Team 1,Team 2,Stage Name,Group Name,Group Stage,...,Away team points in last 5 matches,Home avg goals scored,Home avg goals conceded,Away avg goals scored,Away avg goals conceded,Home Elo,Away Elo,Head to Head Home Team Win,Head to Head Away Team Win,Head to Head Draw
959,960,WC-2022,2022 FIFA World Cup,M-2022-60,England v France,England,France,quarter-finals,not applicable,0,...,12,2.4,0.8,2.6,1.2,1091.61,1176.68,2,0,0
960,961,WC-2022,2022 FIFA World Cup,M-2022-61,Argentina v Croatia,Argentina,Croatia,semi-finals,not applicable,0,...,11,1.8,1.0,1.2,0.6,1180.36,1126.23,1,1,0
961,962,WC-2022,2022 FIFA World Cup,M-2022-62,France v Morocco,France,Morocco,semi-finals,not applicable,0,...,13,2.2,1.0,1.0,0.2,1188.08,1020.80,0,0,0
962,963,WC-2022,2022 FIFA World Cup,M-2022-63,Croatia v Morocco,Croatia,Morocco,third-place match,not applicable,0,...,12,1.2,1.2,1.0,0.6,1113.54,1012.51,0,0,1
963,964,WC-2022,2022 FIFA World Cup,M-2022-64,Argentina v France,Argentina,France,final,not applicable,0,...,12,2.2,0.6,1.8,0.8,1193.04,1196.37,2,1,0

In [248]:
df.shape

(964, 63)

In [249]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 964 entries, 0 to 963
Data columns (total 63 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Key Id                              964 non-null    int64
 1   Tournament Id                       964 non-null    object
 2   tournament Name                     964 non-null    object
 3   Match Id                            964 non-null    object
 4   Match Name                          964 non-null    object
 5   Team 1                              964 non-null    object
 6   Team 2                              964 non-null    object
 7   Stage Name                          964 non-null    object
 8   Group Name                          964 non-null    object
 9   Group Stage                         964 non-null    int64
 10  Knockout Stage                      964 non-null    int64
 11  Replayed                            964 non-null    int64
 12  Replay                              964 non-null    int64
 13  Match Date                          964 non-null    object
 14  Match Time                          964 non-null    object
 15  Stadium Id                          964 non-null    object
 16  Stadium Name                        964 non-null    object
 17  City Name                           964 non-null    object
 18  Country Name                        964 non-null    object
 19  Home Team Id                        964 non-null    object
 20  Home Team Name                      964 non-null    object
 21  Home Team Code                      964 non-null    object
 22  Away Team Id                        964 non-null    object
 23  Away Team Name                      964 non-null    object
 24  Away Team Code                      964 non-null    object
 25  Score                               964 non-null    object
 26  Home Team Score                     964 non-null    int64
 27  Away Team Score                     964 non-null    int64
 28  Home Team Score Margin              964 non-null    int64
 29  Away Team Score Margin              964 non-null    int64
 30  Extra Time                          964 non-null    int64
 31  Penalty Shootout                    964 non-null    int64
 32  Score Penalties                     964 non-null    object
 33  Home Team Score Penalties           964 non-null    int64
 34  Away Team Score Penalties           964 non-null    int64
 35  Result                              964 non-null    object
 36  Home Team Win                       964 non-null    int64
 37  Away Team Win                       964 non-null    int64
 38  Draw                                964 non-null    int64
 39  Home Team FIFA Rank                 964 non-null    float64
 40  Away Team FIFA Rank                 964 non-null    float64
 41  Year                                964 non-null    int64
 42  Home Team Squad Value (€M)          964 non-null    float64
 43  Away Team Squad Value (€M)          964 non-null    float64
 44  Home team win percentage            964 non-null    float64
 45  Away team win percentage            964 non-null    float64
 46  Home team wins in last 5 matches    964 non-null    int64
 47  Home team draws in last 5 matches   964 non-null    int64
 48  Home team losses in last 5 matches  964 non-null    int64
 49  Away team wins in last 5 matches    964 non-null    int64
 50  Away team draws in last 5 matches   964 non-null    int64
 51  Away team losses in last 5 matches  964 non-null    int64
 52  Home team points in last 5 matches  964 non-null    int64
 53  Away team points in last 5 matches  964 non-null    int64
 54  Home avg goals scored               964 non-null    float64
 55  Home avg goals conceded             964 non-null    float64
 56  Away avg goals scored               964 non-null    float64
 57  Away avg goals conceded             964 non-null    float64
 58  Home Elo                            964 non-null    float64
 59  Away Elo                            964 non-null    float64
 60  Head to Head Home Team Win          964 non-null    int64
 61  Head to Head Away Team Win          964 non-null    int64
 62  Head to Head Draw                   964 non-null    int64
dtypes: float64(12), int64(28), object(23)
memory usage: 474.6+ KB

In [250]:
df.describe()

,Key Id,Group Stage,Knockout Stage,Replayed,Replay,Home Team Score,Away Team Score,Home Team Score Margin,Away Team Score Margin,Extra Time,...,Away team points in last 5 matches,Home avg goals scored,Home avg goals conceded,Away avg goals scored,Away avg goals conceded,Home Elo,Away Elo,Head to Head Home Team Win,Head to Head Away Team Win,Head to Head Draw
count,964.00000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,...,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000
mean,482.50000,0.744813,0.255187,0.004149,0.004149,1.766598,1.054979,0.711618,-0.711618,0.075726,...,5.714730,1.509959,1.249948,1.276366,1.436065,1049.448434,1021.189305,0.280083,0.192946,0.104772
std,278.42713,0.436192,0.436192,0.064315,0.064315,1.601040,1.071720,1.925893,1.925893,0.264697,...,3.873727,0.883062,0.786662,0.830956,0.949084,82.983228,68.814003,0.625171,0.501412,0.335535
min,1.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-7.000000,-9.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,868.200000,878.270000,0.000000,0.000000,0.000000
25%,241.75000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,-2.000000,0.000000,...,3.000000,1.000000,0.800000,0.800000,0.800000,990.122500,979.442500,0.000000,0.000000,0.000000
50%,482.50000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,-1.000000,0.000000,...,6.000000,1.400000,1.200000,1.200000,1.333300,1028.915000,1001.920000,0.000000,0.000000,0.000000
75%,723.25000,1.000000,1.000000,0.000000,0.000000,3.000000,2.000000,2.000000,0.000000,0.000000,...,9.000000,2.000000,1.600000,1.800000,1.800000,1096.070000,1048.237500,0.000000,0.000000,0.000000
max,964.00000,1.000000,1.000000,1.000000,1.000000,10.000000,7.000000,9.000000,7.000000,1.000000,...,15.000000,7.000000,6.333300,5.400000,9.000000,1301.140000,1292.130000,4.000000,4.000000,2.000000

In [251]:
df.isna().sum()

Key Id                        0
Tournament Id                 0
tournament Name               0
Match Id                      0
Match Name                    0
                             ..
Home Elo                      0
Away Elo                      0
Head to Head Home Team Win    0
Head to Head Away Team Win    0
Head to Head Draw             0
Length: 63, dtype: int64

In [252]:
df.columns

Index(['Key Id', 'Tournament Id', 'tournament Name', 'Match Id', 'Match Name',
       'Team 1', 'Team 2', 'Stage Name', 'Group Name', 'Group Stage',
       'Knockout Stage', 'Replayed', 'Replay', 'Match Date', 'Match Time',
       'Stadium Id', 'Stadium Name', 'City Name', 'Country Name',
       'Home Team Id', 'Home Team Name', 'Home Team Code', 'Away Team Id',
       'Away Team Name', 'Away Team Code', 'Score', 'Home Team Score',
       'Away Team Score', 'Home Team Score Margin', 'Away Team Score Margin',
       'Extra Time', 'Penalty Shootout', 'Score Penalties',
       'Home Team Score Penalties', 'Away Team Score Penalties', 'Result',
       'Home Team Win', 'Away Team Win', 'Draw', 'Home Team FIFA Rank',
       'Away Team FIFA Rank', 'Year', 'Home Team Squad Value (€M)',
       'Away Team Squad Value (€M)', 'Home team win percentage',
       'Away team win percentage', 'Home team wins in last 5 matches',
       'Home team draws in last 5 matches',
       'Home team losses in last 5 matches',
       'Away team wins in last 5 matches', 'Away team draws in last 5 matches',
       'Away team losses in last 5 matches',
       'Home team points in last 5 matches',
       'Away team points in last 5 matches', 'Home avg goals scored',
       'Home avg goals conceded', 'Away avg goals scored',
       'Away avg goals conceded', 'Home Elo', 'Away Elo',
       'Head to Head Home Team Win', 'Head to Head Away Team Win',
       'Head to Head Draw'],
      dtype='object')

In [253]:
#df["Match Date"].dtype
df["Match Date"]=pd.to_datetime(df['Match Date'],format="mixed")
df["match_day"]=df["Match Date"].dt.day
df["match_month"]=df["Match Date"].dt.month
df["match_year"]=df["Match Date"].dt.year
df.drop("Match Date",axis=1,inplace=True)
df.head()

,Key Id,Tournament Id,tournament Name,Match Id,Match Name,Team 1,Team 2,Stage Name,Group Name,Group Stage,...,Away avg goals scored,Away avg goals conceded,Home Elo,Away Elo,Head to Head Home Team Win,Head to Head Away Team Win,Head to Head Draw,match_day,match_month,match_year
0,1,WC-1930,1930 FIFA World Cup,M-1930-01,France v Mexico,France,Mexico,group stage,Group 1,1,...,0.0,0.0,1000.0,1000.0,0,0,0,13,7,1930
1,2,WC-1930,1930 FIFA World Cup,M-1930-02,United States v Belgium,United States,Belgium,group stage,Group 4,1,...,0.0,0.0,1000.0,1000.0,0,0,0,13,7,1930
2,3,WC-1930,1930 FIFA World Cup,M-1930-03,Yugoslavia v Brazil,Yugoslavia,Brazil,group stage,Group 2,1,...,0.0,0.0,1000.0,1000.0,0,0,0,14,7,1930
3,4,WC-1930,1930 FIFA World Cup,M-1930-04,Romania v Peru,Romania,Peru,group stage,Group 3,1,...,0.0,0.0,1000.0,1000.0,0,0,0,14,7,1930
4,5,WC-1930,1930 FIFA World Cup,M-1930-05,Argentina v France,Argentina,France,group stage,Group 1,1,...,4.0,1.0,1000.0,1015.0,0,0,0,15,7,1930

In [254]:
df["Match Time"]=pd.to_datetime(df["Match Time"],format="mixed")
df["start_time"]=(df["Match Time"].dt.hour+(df["Match Time"].dt.minute)/60)
df.drop("Match Time",axis=1,inplace=True)

In [255]:
# Lower rank number = better team
df['Rank Ratio'] = df['Away Team FIFA Rank'] / df['Home Team FIFA Rank']
# >1 means home team is ranked better, <1 means away team is better
df['Squad Value Ratio'] = df['Home Team Squad Value (€M)'] / df['Away Team Squad Value (€M)']
df['H2H Total'] = df['Head to Head Home Team Win'] + df['Head to Head Away Team Win']
df['H2H Home Win Rate'] = df['Head to Head Home Team Win'] / (df['H2H Total'] + 1)  # +1 avoids div/0
df['H2H Away Win Rate'] = df['Head to Head Away Team Win'] / (df['H2H Total'] + 1)
df['H2H Total'] = df['Head to Head Home Team Win'] + df['Head to Head Away Team Win']
df['H2H Home Win Rate'] = df['Head to Head Home Team Win'] / (df['H2H Total'] + 1)  # +1 avoids div/0
df['H2H Away Win Rate'] = df['Head to Head Away Team Win'] / (df['H2H Total'] + 1)

In [256]:
df["elo difference"]=df["Home Elo"]-df["Away Elo"]
df["Home GD avg"]=df["Home avg goals scored"]-df["Home avg goals conceded"]
df["Away GD avg"]=df["Away avg goals scored"]-df["Away avg goals conceded"]

In [257]:
df["Rank difference"]=(df["Home Team FIFA Rank"]-df["Away Team FIFA Rank"])
df

,Key Id,Tournament Id,tournament Name,Match Id,Match Name,Team 1,Team 2,Stage Name,Group Name,Group Stage,...,start_time,Rank Ratio,Squad Value Ratio,H2H Total,H2H Home Win Rate,H2H Away Win Rate,elo difference,Home GD avg,Away GD avg,Rank difference
0,1,WC-1930,1930 FIFA World Cup,M-1930-01,France v Mexico,France,Mexico,group stage,Group 1,1,...,15.000000,3.333333,3.000000,0,0.000000,0.000000,0.00,0.0,0.0,-14.0
1,2,WC-1930,1930 FIFA World Cup,M-1930-02,United States v Belgium,United States,Belgium,group stage,Group 4,1,...,15.000000,0.800000,0.818182,0,0.000000,0.000000,0.00,0.0,0.0,2.0
2,3,WC-1930,1930 FIFA World Cup,M-1930-03,Yugoslavia v Brazil,Yugoslavia,Brazil,group stage,Group 2,1,...,12.750000,1.250000,1.125000,0,0.000000,0.000000,0.00,0.0,0.0,-1.0
3,4,WC-1930,1930 FIFA World Cup,M-1930-04,Romania v Peru,Romania,Peru,group stage,Group 3,1,...,14.833333,1.285714,1.285714,0,0.000000,0.000000,0.00,0.0,0.0,-4.0
4,5,WC-1930,1930 FIFA World Cup,M-1930-05,Argentina v France,Argentina,France,group stage,Group 1,1,...,16.000000,3.000000,1.466667,0,0.000000,0.000000,-15.00,0.0,3.0,-4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
959,960,WC-2022,2022 FIFA World Cup,M-2022-60,England v France,England,France,quarter-finals,not applicable,0,...,22.000000,0.600000,0.939655,2,0.666667,0.000000,-85.07,1.6,1.4,2.0
960,961,WC-2022,2022 FIFA World Cup,M-2022-61,Argentina v Croatia,Argentina,Croatia,semi-finals,not applicable,0,...,22.000000,3.500000,2.830769,2,0.333333,0.333333,54.13,0.8,0.6,-5.0
961,962,WC-2022,2022 FIFA World Cup,M-2022-62,France v Morocco,France,Morocco,semi-finals,not applicable,0,...,22.000000,3.666667,3.741935,0,0.000000,0.000000,167.28,1.2,0.8,-8.0
962,963,WC-2022,2022 FIFA World Cup,M-2022-63,Croatia v Morocco,Croatia,Morocco,third-place match,not applicable,0,...,18.000000,1.571429,1.048387,0,0.000000,0.000000,101.03,0.0,0.4,-4.0
963,964,WC-2022,2022 FIFA World Cup,M-2022-64,Argentina v France,Argentina,France,final,not applicable,0,...,18.000000,1.500000,0.793103,3,0.500000,0.250000,-3.33,1.6,1.0,-1.0

In [258]:
df["Team value difference"]=(df["Home Team Squad Value (€M)"]-df["Away Team Squad Value (€M)"])
df.tail()

,Key Id,Tournament Id,tournament Name,Match Id,Match Name,Team 1,Team 2,Stage Name,Group Name,Group Stage,...,Rank Ratio,Squad Value Ratio,H2H Total,H2H Home Win Rate,H2H Away Win Rate,elo difference,Home GD avg,Away GD avg,Rank difference,Team value difference
959,960,WC-2022,2022 FIFA World Cup,M-2022-60,England v France,England,France,quarter-finals,not applicable,0,...,0.600000,0.939655,2,0.666667,0.000000,-85.07,1.6,1.4,2.0,-70.0
960,961,WC-2022,2022 FIFA World Cup,M-2022-61,Argentina v Croatia,Argentina,Croatia,semi-finals,not applicable,0,...,3.500000,2.830769,2,0.333333,0.333333,54.13,0.8,0.6,-5.0,595.0
961,962,WC-2022,2022 FIFA World Cup,M-2022-62,France v Morocco,France,Morocco,semi-finals,not applicable,0,...,3.666667,3.741935,0,0.000000,0.000000,167.28,1.2,0.8,-8.0,850.0
962,963,WC-2022,2022 FIFA World Cup,M-2022-63,Croatia v Morocco,Croatia,Morocco,third-place match,not applicable,0,...,1.571429,1.048387,0,0.000000,0.000000,101.03,0.0,0.4,-4.0,15.0
963,964,WC-2022,2022 FIFA World Cup,M-2022-64,Argentina v France,Argentina,France,final,not applicable,0,...,1.500000,0.793103,3,0.500000,0.250000,-3.33,1.6,1.0,-1.0,-240.0

In [259]:
df["Home Team advantage"]=(df["Home Team FIFA Rank"]>df["Away Team FIFA Rank"]).astype(int)
df["Away Team Advantage"]=(df["Away Team FIFA Rank"]>df["Home Team FIFA Rank"]).astype(int)
df["Home Team advantage"]-=(df["Home Team Squad Value (€M)"]>df["Away Team Squad Value (€M)"]).astype(int)
df["Away Team Advantage"]+=(df["Home Team Squad Value (€M)"]<df["Away Team Squad Value (€M)"]).astype(int)
df["Home Team advantage"]-=(df["Home GD avg"]>df["Away GD avg"]).astype(int)
df["Away Team Advantage"]+=(df["Home GD avg"]<df["Away GD avg"]).astype(int)
df["Home Team advantage"]-=(df["Home Elo"]>df["Away Elo"]).astype(int)
df["Away Team Advantage"]+=(df["Home Elo"]<df["Away Elo"]).astype(int)

In [260]:
df["win percent difference"]=df["Home team win percentage"]-df["Away team win percentage"]
df.tail()

,Key Id,Tournament Id,tournament Name,Match Id,Match Name,Team 1,Team 2,Stage Name,Group Name,Group Stage,...,H2H Home Win Rate,H2H Away Win Rate,elo difference,Home GD avg,Away GD avg,Rank difference,Team value difference,Home Team advantage,Away Team Advantage,win percent difference
959,960,WC-2022,2022 FIFA World Cup,M-2022-60,England v France,England,France,quarter-finals,not applicable,0,...,0.666667,0.000000,-85.07,1.6,1.4,2.0,-70.0,0,2,-0.1143
960,961,WC-2022,2022 FIFA World Cup,M-2022-61,Argentina v Croatia,Argentina,Croatia,semi-finals,not applicable,0,...,0.333333,0.333333,54.13,0.8,0.6,-5.0,595.0,-3,1,0.2857
961,962,WC-2022,2022 FIFA World Cup,M-2022-62,France v Morocco,France,Morocco,semi-finals,not applicable,0,...,0.000000,0.000000,167.28,1.2,0.8,-8.0,850.0,-3,1,0.1429
962,963,WC-2022,2022 FIFA World Cup,M-2022-63,Croatia v Morocco,Croatia,Morocco,third-place match,not applicable,0,...,0.000000,0.000000,101.03,0.0,0.4,-4.0,15.0,-2,2,0.0000
963,964,WC-2022,2022 FIFA World Cup,M-2022-64,Argentina v France,Argentina,France,final,not applicable,0,...,0.500000,0.250000,-3.33,1.6,1.0,-1.0,-240.0,-1,3,0.1428

In [261]:
y=df[["Result"]]
df.drop(columns=["Key Id",
                 "Team 1",
                 "Team 2",
                 "Tournament Id",
                 "Group Name",
                 "tournament Name",
                 "Match Id","Year",
                 "Match Name",
                 "Result",
                 'Home Team Id',
                 'Home Team Code',
                 'Away Team Id',
                 'Away Team Code',
                 'Country Name',
                 'Stadium Name',
                 'City Name',
                 'Score',
                 'Score Penalties',
                 'Result',
                 'Score',
                 'Home Team Score',
                 'Away Team Score',
                 'Home Team Score Margin',
                 'Away Team Score Margin',
                 'Extra Time',
                 'Penalty Shootout',
                 'Score Penalties', 
                 'Home Team Score Penalties',
                 'Away Team Score Penalties',
                 'Result', 'Home Team Win',
                 'Away Team Win',
                 'Draw',
                 'Stadium Id'],
                 inplace=True)

In [262]:
df.tail()

,Stage Name,Group Stage,Knockout Stage,Replayed,Replay,Home Team Name,Away Team Name,Home Team FIFA Rank,Away Team FIFA Rank,Home Team Squad Value (€M),...,H2H Home Win Rate,H2H Away Win Rate,elo difference,Home GD avg,Away GD avg,Rank difference,Team value difference,Home Team advantage,Away Team Advantage,win percent difference
959,quarter-finals,0,1,0,0,England,France,5.0,3.0,1090.0,...,0.666667,0.000000,-85.07,1.6,1.4,2.0,-70.0,0,2,-0.1143
960,semi-finals,0,1,0,0,Argentina,Croatia,2.0,7.0,920.0,...,0.333333,0.333333,54.13,0.8,0.6,-5.0,595.0,-3,1,0.2857
961,semi-finals,0,1,0,0,France,Morocco,3.0,11.0,1160.0,...,0.000000,0.000000,167.28,1.2,0.8,-8.0,850.0,-3,1,0.1429
962,third-place match,0,1,0,0,Croatia,Morocco,7.0,11.0,325.0,...,0.000000,0.000000,101.03,0.0,0.4,-4.0,15.0,-2,2,0.0000
963,final,0,1,0,0,Argentina,France,2.0,3.0,920.0,...,0.500000,0.250000,-3.33,1.6,1.0,-1.0,-240.0,-1,3,0.1428

In [263]:
#categorical =x.select_dtypes(include="object").columns
categorical=[col for col in df.columns if df[col].dtype=="object"]
categorical

['Stage Name', 'Home Team Name', 'Away Team Name']

In [264]:
#chi2-square test
related_columns={}
not_related_columns={}

for col in categorical:
    table=pd.crosstab(df[col],y["Result"])
    chi2,p,dof,expected=chi2_contingency(table)
    if p>=0.05:
        not_related_columns[col]=p
    else:
        related_columns[col]=p

print("related_columns",related_columns)
print("\n not_related_columns",not_related_columns)

related_columns {'Stage Name': np.float64(3.9626824582397054e-10), 'Home Team Name': np.float64(2.8924492152421955e-11), 'Away Team Name': np.float64(0.012825406034170617)}

 not_related_columns {}

In [265]:
#annova_test
numeric_col=[col for col in df.columns if df[col].dtypes!="object"]
numeric_col

['Group Stage',
 'Knockout Stage',
 'Replayed',
 'Replay',
 'Home Team FIFA Rank',
 'Away Team FIFA Rank',
 'Home Team Squad Value (€M)',
 'Away Team Squad Value (€M)',
 'Home team win percentage',
 'Away team win percentage',
 'Home team wins in last 5 matches',
 'Home team draws in last 5 matches',
 'Home team losses in last 5 matches',
 'Away team wins in last 5 matches',
 'Away team draws in last 5 matches',
 'Away team losses in last 5 matches',
 'Home team points in last 5 matches',
 'Away team points in last 5 matches',
 'Home avg goals scored',
 'Home avg goals conceded',
 'Away avg goals scored',
 'Away avg goals conceded',
 'Home Elo',
 'Away Elo',
 'Head to Head Home Team Win',
 'Head to Head Away Team Win',
 'Head to Head Draw',
 'match_day',
 'match_month',
 'match_year',
 'start_time',
 'Rank Ratio',
 'Squad Value Ratio',
 'H2H Total',
 'H2H Home Win Rate',
 'H2H Away Win Rate',
 'elo difference',
 'Home GD avg',
 'Away GD avg',
 'Rank difference',
 'Team value difference',
 'Home Team advantage',
 'Away Team Advantage',
 'win percent difference']

In [266]:
#annova_test
related_numeric_columns={}
not_related_numeric_columns={}
for col in numeric_col:
    Away=df[y["Result"]==0][col]
    Draw=df[y["Result"]==1][col]
    Home=df[y["Result"]==2][col]
    f_stats,p_value=f_oneway(Away,Draw,Home)
    if p_value>=0.05:
        not_related_numeric_columns[col]=p_value
    else:
        related_numeric_columns[col]=p_value

print("related_numeric_columns : ",related_numeric_columns)
print("not_related_numeric_columns : ",not_related_numeric_columns)

related_numeric_columns :  {'Group Stage': np.float64(nan), 'Knockout Stage': np.float64(nan), 'Replayed': np.float64(nan), 'Replay': np.float64(nan), 'Home Team FIFA Rank': np.float64(nan), 'Away Team FIFA Rank': np.float64(nan), 'Home Team Squad Value (€M)': np.float64(nan), 'Away Team Squad Value (€M)': np.float64(nan), 'Home team win percentage': np.float64(nan), 'Away team win percentage': np.float64(nan), 'Home team wins in last 5 matches': np.float64(nan), 'Home team draws in last 5 matches': np.float64(nan), 'Home team losses in last 5 matches': np.float64(nan), 'Away team wins in last 5 matches': np.float64(nan), 'Away team draws in last 5 matches': np.float64(nan), 'Away team losses in last 5 matches': np.float64(nan), 'Home team points in last 5 matches': np.float64(nan), 'Away team points in last 5 matches': np.float64(nan), 'Home avg goals scored': np.float64(nan), 'Home avg goals conceded': np.float64(nan), 'Away avg goals scored': np.float64(nan), 'Away avg goals conceded': np.float64(nan), 'Home Elo': np.float64(nan), 'Away Elo': np.float64(nan), 'Head to Head Home Team Win': np.float64(nan), 'Head to Head Away Team Win': np.float64(nan), 'Head to Head Draw': np.float64(nan), 'match_day': np.float64(nan), 'match_month': np.float64(nan), 'match_year': np.float64(nan), 'start_time': np.float64(nan), 'Rank Ratio': np.float64(nan), 'Squad Value Ratio': np.float64(nan), 'H2H Total': np.float64(nan), 'H2H Home Win Rate': np.float64(nan), 'H2H Away Win Rate': np.float64(nan), 'elo difference': np.float64(nan), 'Home GD avg': np.float64(nan), 'Away GD avg': np.float64(nan), 'Rank difference': np.float64(nan), 'Team value difference': np.float64(nan), 'Home Team advantage': np.float64(nan), 'Away Team Advantage': np.float64(nan), 'win percent difference': np.float64(nan)}
not_related_numeric_columns :  {}

C:\Users\Abhishek k\AppData\Local\Temp\ipykernel_5928\3907210790.py:8: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  f_stats,p_value=f_oneway(Away,Draw,Home)

In [267]:
y

            Result
0    home team win
1    home team win
2    home team win
3    home team win
4    home team win
..             ...
959  away team win
960  home team win
961  home team win
962  home team win
963  home team win

[964 rows x 1 columns]

In [268]:
y["Result"]=y["Result"].map({"draw": 0,"away team win": 1,"home team win": 2 })
y

C:\Users\Abhishek k\AppData\Local\Temp\ipykernel_5928\1451611114.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y["Result"]=y["Result"].map({"draw": 0,"away team win": 1,"home team win": 2 })

     Result
0         2
1         2
2         2
3         2
4         2
..      ...
959       1
960       2
961       2
962       2
963       2

[964 rows x 1 columns]

In [269]:
df["Stage Name"].unique()

array(['group stage', 'semi-finals', 'final', 'round of 16',
       'quarter-finals', 'third-place match', 'final round',
       'second group stage'], dtype=object)

In [270]:
df["Stage Name"]=df["Stage Name"].map({"group stage":0,"second group stage":0, "round of 32":1, "round of 16":2, "quarter-finals":3, "semi-finals":4,"third-place match":4, "final round":5,"final":5})
df.tail()

,Stage Name,Group Stage,Knockout Stage,Replayed,Replay,Home Team Name,Away Team Name,Home Team FIFA Rank,Away Team FIFA Rank,Home Team Squad Value (€M),...,H2H Home Win Rate,H2H Away Win Rate,elo difference,Home GD avg,Away GD avg,Rank difference,Team value difference,Home Team advantage,Away Team Advantage,win percent difference
959,3,0,1,0,0,England,France,5.0,3.0,1090.0,...,0.666667,0.000000,-85.07,1.6,1.4,2.0,-70.0,0,2,-0.1143
960,4,0,1,0,0,Argentina,Croatia,2.0,7.0,920.0,...,0.333333,0.333333,54.13,0.8,0.6,-5.0,595.0,-3,1,0.2857
961,4,0,1,0,0,France,Morocco,3.0,11.0,1160.0,...,0.000000,0.000000,167.28,1.2,0.8,-8.0,850.0,-3,1,0.1429
962,4,0,1,0,0,Croatia,Morocco,7.0,11.0,325.0,...,0.000000,0.000000,101.03,0.0,0.4,-4.0,15.0,-2,2,0.0000
963,5,0,1,0,0,Argentina,France,2.0,3.0,920.0,...,0.500000,0.250000,-3.33,1.6,1.0,-1.0,-240.0,-1,3,0.1428

In [271]:
x_train,x_test,y_train,y_test=train_test_split(df,y,test_size=0.2,random_state=42,stratify=y)
x_train

,Stage Name,Group Stage,Knockout Stage,Replayed,Replay,Home Team Name,Away Team Name,Home Team FIFA Rank,Away Team FIFA Rank,Home Team Squad Value (€M),...,H2H Home Win Rate,H2H Away Win Rate,elo difference,Home GD avg,Away GD avg,Rank difference,Team value difference,Home Team advantage,Away Team Advantage,win percent difference
616,0,1,0,0,0,Nigeria,England,29.0,7.0,65.0,...,0.000000,0.0,-110.70,-1.2,0.4,22.0,-295.0,1,3,-0.4000
642,4,0,1,0,0,South Korea,Turkey,40.0,9.0,50.0,...,0.000000,0.5,-48.86,0.2,0.8,31.0,-45.0,1,3,0.0000
831,3,0,1,0,0,Netherlands,Costa Rica,5.0,16.0,580.0,...,0.000000,0.0,148.48,1.4,0.4,-11.0,520.0,-3,1,0.2571
531,0,1,0,0,0,Germany,United States,3.0,22.0,310.0,...,0.000000,0.0,238.32,0.4,-0.4,-19.0,255.0,-3,1,0.6000
914,0,1,0,0,0,Portugal,Ghana,9.0,58.0,870.0,...,0.500000,0.0,69.01,0.2,-0.2,-49.0,750.0,-3,1,0.2667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
363,0,1,0,0,0,Argentina,South Korea,1.0,28.0,35.0,...,0.000000,0.0,76.34,0.2,-8.0,-27.0,31.0,-3,1,0.8571
404,3,0,1,0,0,Brazil,France,5.0,3.0,30.0,...,0.500000,0.0,180.60,1.6,1.0,2.0,2.0,-2,0,0.0857
415,0,1,0,0,0,Italy,Austria,3.0,16.0,50.0,...,0.666667,0.0,93.24,0.2,0.2,-13.0,40.0,-3,1,0.5238
309,0,1,0,0,0,Italy,Poland,1.0,3.0,30.0,...,0.000000,0.5,8.41,0.0,0.0,-2.0,18.0,-2,1,0.1428
494,0,1,0,0,0,Russia,Cameroon,13.0,31.0,70.0,...,0.000000,0.0,-37.71,-2.0,-1.4,-18.0,25.0,-1,3,0.3333

In [272]:
#encoder = OneHotEncoder(sparse_output=False)
encoder=TargetEncoder(smooth="auto",cv=5,random_state=42,target_type="continuous")
y_train=y_train["Result"]
for col in categorical:
    if col!='Stage Name':
        x_train[col]=encoder.fit_transform(x_train[[col]],y_train).ravel()
        x_test[col]=encoder.fit_transform(x_test[[col]],y_test).ravel()

c:\Users\Abhishek k\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\Abhishek k\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
parms={
    "objective":"multi:softmax",
    "num_class":3,
    "max_depth":4,
    "learning_rate":0.02,
    "n_estimators":100,
    "alpha":0.5
}
xgmodel = XGBClassifier(
    objective="multi:softmax",
    num_class=3,
    max_depth=6,
    learning_rate=0.01,
    n_estimators=300,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)
#xgmodel=XGBClassifier(**parms)
bagging=BaggingClassifier(xgmodel,n_estimators=10,random_state=42)
bagging.fit(x_train,y_train)
y_pred_bagging=bagging.predict(x_test)
print("Classification Report \n\n",classification_report(y_test,y_pred_bagging))
print("\nConfusion Matrix\n\n",confusion_matrix(y_test,y_pred_bagging))