**PREPROCESSING**

In [559]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from scipy.stats import chi2_contingency
from scipy.stats import f_oneway
from imblearn.over_sampling import SMOTE

from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [560]:
df = pd.read_csv("C:\\Users\\Abhishek k\\OneDrive\\Documents\\projects\\mini project ml\\Dataset\\dataset.csv")

In [561]:
df.tail()

,Key Id,Tournament Id,tournament Name,Match Id,Match Name,Team 1,Team 2,Stage Name,Group Name,Group Stage,...,H2H_Home_Wins_Last5,H2H_Away_Wins_Last5,Home_Team_Form_Last5,Away_Team_Form_Last5,Home_Team_Goals_Scored_Last5,Home_Team_Goals_Conceded_Last5,Home_Team_Win_Pct,Away_Team_Win_Pct,Away_Team_Goals_Scored_Last5,Away_Team_Goals_Conceded_Last5
959,960,WC-2022,2022 FIFA World Cup,M-2022-60,England v France,England,France,quarter-finals,not applicable,0,...,2,0,3,4,12,4,45.21,55.71,13,6
960,961,WC-2022,2022 FIFA World Cup,M-2022-61,Argentina v Croatia,Argentina,Croatia,semi-finals,not applicable,0,...,1,1,4,3,9,5,59.30,57.14,6,3
961,962,WC-2022,2022 FIFA World Cup,M-2022-62,France v Morocco,France,Morocco,semi-finals,not applicable,0,...,0,0,4,4,11,5,56.34,28.57,5,1
962,963,WC-2022,2022 FIFA World Cup,M-2022-63,Croatia v Morocco,Croatia,Morocco,third-place match,not applicable,0,...,0,0,3,4,6,6,55.17,27.27,5,3
963,964,WC-2022,2022 FIFA World Cup,M-2022-64,Argentina v France,Argentina,France,final,not applicable,0,...,2,1,5,4,11,3,59.77,56.94,9,4

In [562]:
df.shape

(964, 54)

In [563]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 964 entries, 0 to 963
Data columns (total 54 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Key Id                          964 non-null    int64
 1   Tournament Id                   964 non-null    object
 2   tournament Name                 964 non-null    object
 3   Match Id                        964 non-null    object
 4   Match Name                      964 non-null    object
 5   Team 1                          964 non-null    object
 6   Team 2                          964 non-null    object
 7   Stage Name                      964 non-null    object
 8   Group Name                      964 non-null    object
 9   Group Stage                     964 non-null    int64
 10  Knockout Stage                  964 non-null    int64
 11  Replayed                        964 non-null    int64
 12  Replay                          964 non-null    int64
 13  Match Date                      964 non-null    object
 14  Match Time                      964 non-null    object
 15  Stadium Id                      964 non-null    object
 16  Stadium Name                    964 non-null    object
 17  City Name                       964 non-null    object
 18  Country Name                    964 non-null    object
 19  Home Team Id                    964 non-null    object
 20  Home Team Name                  964 non-null    object
 21  Home Team Code                  964 non-null    object
 22  Away Team Id                    964 non-null    object
 23  Away Team Name                  964 non-null    object
 24  Away Team Code                  964 non-null    object
 25  Score                           964 non-null    object
 26  Home Team Score                 964 non-null    int64
 27  Away Team Score                 964 non-null    int64
 28  Home Team Score Margin          964 non-null    int64
 29  Away Team Score Margin          964 non-null    int64
 30  Extra Time                      964 non-null    int64
 31  Penalty Shootout                964 non-null    int64
 32  Score Penalties                 964 non-null    object
 33  Home Team Score Penalties       964 non-null    int64
 34  Away Team Score Penalties       964 non-null    int64
 35  Result                          964 non-null    object
 36  Home Team Win                   964 non-null    int64
 37  Away Team Win                   964 non-null    int64
 38  Draw                            964 non-null    int64
 39  Home Team FIFA Rank             964 non-null    float64
 40  Away Team FIFA Rank             964 non-null    float64
 41  Year                            964 non-null    int64
 42  Home Team Squad Value (€M)      964 non-null    float64
 43  Away Team Squad Value (€M)      964 non-null    float64
 44  H2H_Home_Wins_Last5             964 non-null    int64
 45  H2H_Away_Wins_Last5             964 non-null    int64
 46  Home_Team_Form_Last5            964 non-null    int64
 47  Away_Team_Form_Last5            964 non-null    int64
 48  Home_Team_Goals_Scored_Last5    964 non-null    int64
 49  Home_Team_Goals_Conceded_Last5  964 non-null    int64
 50  Home_Team_Win_Pct               964 non-null    float64
 51  Away_Team_Win_Pct               964 non-null    float64
 52  Away_Team_Goals_Scored_Last5    964 non-null    int64
 53  Away_Team_Goals_Conceded_Last5  964 non-null    int64
dtypes: float64(6), int64(25), object(23)
memory usage: 406.8+ KB

In [564]:
df.describe()

,Key Id,Group Stage,Knockout Stage,Replayed,Replay,Home Team Score,Away Team Score,Home Team Score Margin,Away Team Score Margin,Extra Time,...,H2H_Home_Wins_Last5,H2H_Away_Wins_Last5,Home_Team_Form_Last5,Away_Team_Form_Last5,Home_Team_Goals_Scored_Last5,Home_Team_Goals_Conceded_Last5,Home_Team_Win_Pct,Away_Team_Win_Pct,Away_Team_Goals_Scored_Last5,Away_Team_Goals_Conceded_Last5
count,964.00000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,...,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000
mean,482.50000,0.744813,0.255187,0.004149,0.004149,1.766598,1.054979,0.711618,-0.711618,0.075726,...,0.251037,0.168050,2.110996,1.618257,7.030083,5.718880,43.194253,36.461349,5.827801,6.206432
std,278.42713,0.436192,0.436192,0.064315,0.064315,1.601040,1.071720,1.925893,1.925893,0.264697,...,0.573967,0.461133,1.378941,1.320624,4.153859,3.515699,23.005892,24.308755,3.929997,3.894496
min,1.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-7.000000,-9.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,241.75000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,-2.000000,0.000000,...,0.000000,0.000000,1.000000,1.000000,4.000000,3.000000,28.570000,20.000000,3.000000,4.000000
50%,482.50000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,-1.000000,0.000000,...,0.000000,0.000000,2.000000,1.000000,7.000000,5.000000,46.075000,38.460000,5.000000,6.000000
75%,723.25000,1.000000,1.000000,0.000000,0.000000,3.000000,2.000000,2.000000,0.000000,0.000000,...,0.000000,0.000000,3.000000,2.250000,9.000000,8.000000,57.890000,52.502500,8.000000,8.000000
max,964.00000,1.000000,1.000000,1.000000,1.000000,10.000000,7.000000,9.000000,7.000000,1.000000,...,4.000000,4.000000,5.000000,5.000000,28.000000,21.000000,100.000000,100.000000,27.000000,23.000000

In [565]:
df.isna().sum()

Key Id                            0
Tournament Id                     0
tournament Name                   0
Match Id                          0
Match Name                        0
Team 1                            0
Team 2                            0
Stage Name                        0
Group Name                        0
Group Stage                       0
Knockout Stage                    0
Replayed                          0
Replay                            0
Match Date                        0
Match Time                        0
Stadium Id                        0
Stadium Name                      0
City Name                         0
Country Name                      0
Home Team Id                      0
Home Team Name                    0
Home Team Code                    0
Away Team Id                      0
Away Team Name                    0
Away Team Code                    0
Score                             0
Home Team Score                   0
Away Team Score                   0
Home Team Score Margin            0
Away Team Score Margin            0
Extra Time                        0
Penalty Shootout                  0
Score Penalties                   0
Home Team Score Penalties         0
Away Team Score Penalties         0
Result                            0
Home Team Win                     0
Away Team Win                     0
Draw                              0
Home Team FIFA Rank               0
Away Team FIFA Rank               0
Year                              0
Home Team Squad Value (€M)        0
Away Team Squad Value (€M)        0
H2H_Home_Wins_Last5               0
H2H_Away_Wins_Last5               0
Home_Team_Form_Last5              0
Away_Team_Form_Last5              0
Home_Team_Goals_Scored_Last5      0
Home_Team_Goals_Conceded_Last5    0
Home_Team_Win_Pct                 0
Away_Team_Win_Pct                 0
Away_Team_Goals_Scored_Last5      0
Away_Team_Goals_Conceded_Last5    0
dtype: int64

In [566]:
df.columns

Index(['Key Id', 'Tournament Id', 'tournament Name', 'Match Id', 'Match Name',
       'Team 1', 'Team 2', 'Stage Name', 'Group Name', 'Group Stage',
       'Knockout Stage', 'Replayed', 'Replay', 'Match Date', 'Match Time',
       'Stadium Id', 'Stadium Name', 'City Name', 'Country Name',
       'Home Team Id', 'Home Team Name', 'Home Team Code', 'Away Team Id',
       'Away Team Name', 'Away Team Code', 'Score', 'Home Team Score',
       'Away Team Score', 'Home Team Score Margin', 'Away Team Score Margin',
       'Extra Time', 'Penalty Shootout', 'Score Penalties',
       'Home Team Score Penalties', 'Away Team Score Penalties', 'Result',
       'Home Team Win', 'Away Team Win', 'Draw', 'Home Team FIFA Rank',
       'Away Team FIFA Rank', 'Year', 'Home Team Squad Value (€M)',
       'Away Team Squad Value (€M)', 'H2H_Home_Wins_Last5',
       'H2H_Away_Wins_Last5', 'Home_Team_Form_Last5', 'Away_Team_Form_Last5',
       'Home_Team_Goals_Scored_Last5', 'Home_Team_Goals_Conceded_Last5',
       'Home_Team_Win_Pct', 'Away_Team_Win_Pct',
       'Away_Team_Goals_Scored_Last5', 'Away_Team_Goals_Conceded_Last5'],
      dtype='object')

In [567]:
#df["Match Date"].dtype
df["Match Date"]=pd.to_datetime(df['Match Date'],format="mixed")
df["match_day"]=df["Match Date"].dt.day
df["match_month"]=df["Match Date"].dt.month
df["match_year"]=df["Match Date"].dt.year
df.drop("Match Date",axis=1,inplace=True)
df.head()

,Key Id,Tournament Id,tournament Name,Match Id,Match Name,Team 1,Team 2,Stage Name,Group Name,Group Stage,...,Away_Team_Form_Last5,Home_Team_Goals_Scored_Last5,Home_Team_Goals_Conceded_Last5,Home_Team_Win_Pct,Away_Team_Win_Pct,Away_Team_Goals_Scored_Last5,Away_Team_Goals_Conceded_Last5,match_day,match_month,match_year
0,1,WC-1930,1930 FIFA World Cup,M-1930-01,France v Mexico,France,Mexico,group stage,Group 1,1,...,0,0,0,0.0,0.0,0,0,13,7,1930
1,2,WC-1930,1930 FIFA World Cup,M-1930-02,United States v Belgium,United States,Belgium,group stage,Group 4,1,...,0,0,0,0.0,0.0,0,0,13,7,1930
2,3,WC-1930,1930 FIFA World Cup,M-1930-03,Yugoslavia v Brazil,Yugoslavia,Brazil,group stage,Group 2,1,...,0,0,0,0.0,0.0,0,0,14,7,1930
3,4,WC-1930,1930 FIFA World Cup,M-1930-04,Romania v Peru,Romania,Peru,group stage,Group 3,1,...,0,0,0,0.0,0.0,0,0,14,7,1930
4,5,WC-1930,1930 FIFA World Cup,M-1930-05,Argentina v France,Argentina,France,group stage,Group 1,1,...,1,0,0,0.0,100.0,4,1,15,7,1930

In [568]:
df.drop(["Year"],axis=1,inplace=True )
df.head()

,Key Id,Tournament Id,tournament Name,Match Id,Match Name,Team 1,Team 2,Stage Name,Group Name,Group Stage,...,Away_Team_Form_Last5,Home_Team_Goals_Scored_Last5,Home_Team_Goals_Conceded_Last5,Home_Team_Win_Pct,Away_Team_Win_Pct,Away_Team_Goals_Scored_Last5,Away_Team_Goals_Conceded_Last5,match_day,match_month,match_year
0,1,WC-1930,1930 FIFA World Cup,M-1930-01,France v Mexico,France,Mexico,group stage,Group 1,1,...,0,0,0,0.0,0.0,0,0,13,7,1930
1,2,WC-1930,1930 FIFA World Cup,M-1930-02,United States v Belgium,United States,Belgium,group stage,Group 4,1,...,0,0,0,0.0,0.0,0,0,13,7,1930
2,3,WC-1930,1930 FIFA World Cup,M-1930-03,Yugoslavia v Brazil,Yugoslavia,Brazil,group stage,Group 2,1,...,0,0,0,0.0,0.0,0,0,14,7,1930
3,4,WC-1930,1930 FIFA World Cup,M-1930-04,Romania v Peru,Romania,Peru,group stage,Group 3,1,...,0,0,0,0.0,0.0,0,0,14,7,1930
4,5,WC-1930,1930 FIFA World Cup,M-1930-05,Argentina v France,Argentina,France,group stage,Group 1,1,...,1,0,0,0.0,100.0,4,1,15,7,1930

In [569]:
df["Match Time"]=pd.to_datetime(df["Match Time"],format="mixed")
df["start_time"]=(df["Match Time"].dt.hour+(df["Match Time"].dt.minute)/60)
df.drop("Match Time",axis=1,inplace=True)

In [570]:
df["Rank difference"]=(df["Home Team FIFA Rank"]-df["Away Team FIFA Rank"])
#df["Away Rank Advantage"]=(df["Away Team FIFA Rank"]<df["Home Team FIFA Rank"]).astype(int)
df

,Key Id,Tournament Id,tournament Name,Match Id,Match Name,Team 1,Team 2,Stage Name,Group Name,Group Stage,...,Home_Team_Goals_Conceded_Last5,Home_Team_Win_Pct,Away_Team_Win_Pct,Away_Team_Goals_Scored_Last5,Away_Team_Goals_Conceded_Last5,match_day,match_month,match_year,start_time,Rank difference
0,1,WC-1930,1930 FIFA World Cup,M-1930-01,France v Mexico,France,Mexico,group stage,Group 1,1,...,0,0.00,0.00,0,0,13,7,1930,15.000000,-14.0
1,2,WC-1930,1930 FIFA World Cup,M-1930-02,United States v Belgium,United States,Belgium,group stage,Group 4,1,...,0,0.00,0.00,0,0,13,7,1930,15.000000,2.0
2,3,WC-1930,1930 FIFA World Cup,M-1930-03,Yugoslavia v Brazil,Yugoslavia,Brazil,group stage,Group 2,1,...,0,0.00,0.00,0,0,14,7,1930,12.750000,-1.0
3,4,WC-1930,1930 FIFA World Cup,M-1930-04,Romania v Peru,Romania,Peru,group stage,Group 3,1,...,0,0.00,0.00,0,0,14,7,1930,14.833333,-4.0
4,5,WC-1930,1930 FIFA World Cup,M-1930-05,Argentina v France,Argentina,France,group stage,Group 1,1,...,0,0.00,100.00,4,1,15,7,1930,16.000000,-4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
959,960,WC-2022,2022 FIFA World Cup,M-2022-60,England v France,England,France,quarter-finals,not applicable,0,...,4,45.21,55.71,13,6,10,12,2022,22.000000,2.0
960,961,WC-2022,2022 FIFA World Cup,M-2022-61,Argentina v Croatia,Argentina,Croatia,semi-finals,not applicable,0,...,5,59.30,57.14,6,3,13,12,2022,22.000000,-5.0
961,962,WC-2022,2022 FIFA World Cup,M-2022-62,France v Morocco,France,Morocco,semi-finals,not applicable,0,...,5,56.34,28.57,5,1,14,12,2022,22.000000,-8.0
962,963,WC-2022,2022 FIFA World Cup,M-2022-63,Croatia v Morocco,Croatia,Morocco,third-place match,not applicable,0,...,6,55.17,27.27,5,3,17,12,2022,18.000000,-4.0
963,964,WC-2022,2022 FIFA World Cup,M-2022-64,Argentina v France,Argentina,France,final,not applicable,0,...,3,59.77,56.94,9,4,18,12,2022,18.000000,-1.0

In [571]:
df["Team value difference"]=(df["Home Team Squad Value (€M)"]-df["Away Team Squad Value (€M)"])
#df["Away Team value advantage"]=(df["Away Team Squad Value (€M)"]>df["Home Team Squad Value (€M)"]).astype(int)
df.tail()

,Key Id,Tournament Id,tournament Name,Match Id,Match Name,Team 1,Team 2,Stage Name,Group Name,Group Stage,...,Home_Team_Win_Pct,Away_Team_Win_Pct,Away_Team_Goals_Scored_Last5,Away_Team_Goals_Conceded_Last5,match_day,match_month,match_year,start_time,Rank difference,Team value difference
959,960,WC-2022,2022 FIFA World Cup,M-2022-60,England v France,England,France,quarter-finals,not applicable,0,...,45.21,55.71,13,6,10,12,2022,22.0,2.0,-70.0
960,961,WC-2022,2022 FIFA World Cup,M-2022-61,Argentina v Croatia,Argentina,Croatia,semi-finals,not applicable,0,...,59.30,57.14,6,3,13,12,2022,22.0,-5.0,595.0
961,962,WC-2022,2022 FIFA World Cup,M-2022-62,France v Morocco,France,Morocco,semi-finals,not applicable,0,...,56.34,28.57,5,1,14,12,2022,22.0,-8.0,850.0
962,963,WC-2022,2022 FIFA World Cup,M-2022-63,Croatia v Morocco,Croatia,Morocco,third-place match,not applicable,0,...,55.17,27.27,5,3,17,12,2022,18.0,-4.0,15.0
963,964,WC-2022,2022 FIFA World Cup,M-2022-64,Argentina v France,Argentina,France,final,not applicable,0,...,59.77,56.94,9,4,18,12,2022,18.0,-1.0,-240.0

In [572]:
y=df[["Result"]]
df.drop(columns=["Key Id", "Tournament Id","Group Name","tournament Name", "Match Id", "Match Name","Result",'Home Team Id','Home Team Code', 'Away Team Id','Away Team Code','Country Name', 'Stadium Name','City Name','Score', 'Score Penalties','Result', 'Score', 'Home Team Score', 'Away Team Score','Home Team Score Margin', 'Away Team Score Margin', 'Extra Time','Penalty Shootout', 'Score Penalties', 'Home Team Score Penalties','Away Team Score Penalties', 'Result', 'Home Team Win', 'Away Team Win','Draw','Stadium Id'], inplace=True)

In [573]:
df

,Team 1,Team 2,Stage Name,Group Stage,Knockout Stage,Replayed,Replay,Home Team Name,Away Team Name,Home Team FIFA Rank,...,Home_Team_Win_Pct,Away_Team_Win_Pct,Away_Team_Goals_Scored_Last5,Away_Team_Goals_Conceded_Last5,match_day,match_month,match_year,start_time,Rank difference,Team value difference
0,France,Mexico,group stage,1,0,0,0,France,Mexico,6.0,...,0.00,0.00,0,0,13,7,1930,15.000000,-14.0,1.0
1,United States,Belgium,group stage,1,0,0,0,United States,Belgium,10.0,...,0.00,0.00,0,0,13,7,1930,15.000000,2.0,-0.2
2,Yugoslavia,Brazil,group stage,1,0,0,0,Yugoslavia,Brazil,4.0,...,0.00,0.00,0,0,14,7,1930,12.750000,-1.0,0.2
3,Romania,Peru,group stage,1,0,0,0,Romania,Peru,14.0,...,0.00,0.00,0,0,14,7,1930,14.833333,-4.0,0.2
4,Argentina,France,group stage,1,0,0,0,Argentina,France,2.0,...,0.00,100.00,4,1,15,7,1930,16.000000,-4.0,0.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
959,England,France,quarter-finals,0,1,0,0,England,France,5.0,...,45.21,55.71,13,6,10,12,2022,22.000000,2.0,-70.0
960,Argentina,Croatia,semi-finals,0,1,0,0,Argentina,Croatia,2.0,...,59.30,57.14,6,3,13,12,2022,22.000000,-5.0,595.0
961,France,Morocco,semi-finals,0,1,0,0,France,Morocco,3.0,...,56.34,28.57,5,1,14,12,2022,22.000000,-8.0,850.0
962,Croatia,Morocco,third-place match,0,1,0,0,Croatia,Morocco,7.0,...,55.17,27.27,5,3,17,12,2022,18.000000,-4.0,15.0
963,Argentina,France,final,0,1,0,0,Argentina,France,2.0,...,59.77,56.94,9,4,18,12,2022,18.000000,-1.0,-240.0

In [574]:
#categorical =x.select_dtypes(include="object").columns
categorical=[col for col in df.columns if df[col].dtype=="object"]
categorical

['Team 1', 'Team 2', 'Stage Name', 'Home Team Name', 'Away Team Name']

In [575]:
#chi2-square test
related_columns={}
not_related_columns={}
for col in categorical:
    table=pd.crosstab(df[col],y["Result"])
    chi2,p,dof,expected=chi2_contingency(table)
    if p>=0.05:
        not_related_columns[col]=p
    else:
        related_columns[col]=p

print("related_columns",related_columns)
print("\n not_related_columns",not_related_columns)

related_columns {'Team 1': np.float64(2.8924492152421955e-11), 'Team 2': np.float64(0.012825406034170617), 'Stage Name': np.float64(3.9626824582397054e-10), 'Home Team Name': np.float64(2.8924492152421955e-11), 'Away Team Name': np.float64(0.012825406034170617)}

 not_related_columns {}

In [576]:
#annova_test
numeric_col=[col for col in df.columns if df[col].dtypes!="object"]
numeric_col

['Group Stage',
 'Knockout Stage',
 'Replayed',
 'Replay',
 'Home Team FIFA Rank',
 'Away Team FIFA Rank',
 'Home Team Squad Value (€M)',
 'Away Team Squad Value (€M)',
 'H2H_Home_Wins_Last5',
 'H2H_Away_Wins_Last5',
 'Home_Team_Form_Last5',
 'Away_Team_Form_Last5',
 'Home_Team_Goals_Scored_Last5',
 'Home_Team_Goals_Conceded_Last5',
 'Home_Team_Win_Pct',
 'Away_Team_Win_Pct',
 'Away_Team_Goals_Scored_Last5',
 'Away_Team_Goals_Conceded_Last5',
 'match_day',
 'match_month',
 'match_year',
 'start_time',
 'Rank difference',
 'Team value difference']

In [577]:
#annova_test
related_numeric_columns={}
not_related_numeric_columns={}
for col in numeric_col:
    Away=df[y["Result"]==0][col]
    Draw=df[y["Result"]==1][col]
    Home=df[y["Result"]==2][col]
    f_stats,p_value=f_oneway(Away,Draw,Home)
    if p_value>=0.05:
        not_related_numeric_columns[col]=p_value
    else:
        related_numeric_columns[col]=p_value

print("related_numeric_columns : ",related_numeric_columns)
print("not_related_numeric_columns : ",not_related_numeric_columns)

related_numeric_columns :  {'Group Stage': np.float64(nan), 'Knockout Stage': np.float64(nan), 'Replayed': np.float64(nan), 'Replay': np.float64(nan), 'Home Team FIFA Rank': np.float64(nan), 'Away Team FIFA Rank': np.float64(nan), 'Home Team Squad Value (€M)': np.float64(nan), 'Away Team Squad Value (€M)': np.float64(nan), 'H2H_Home_Wins_Last5': np.float64(nan), 'H2H_Away_Wins_Last5': np.float64(nan), 'Home_Team_Form_Last5': np.float64(nan), 'Away_Team_Form_Last5': np.float64(nan), 'Home_Team_Goals_Scored_Last5': np.float64(nan), 'Home_Team_Goals_Conceded_Last5': np.float64(nan), 'Home_Team_Win_Pct': np.float64(nan), 'Away_Team_Win_Pct': np.float64(nan), 'Away_Team_Goals_Scored_Last5': np.float64(nan), 'Away_Team_Goals_Conceded_Last5': np.float64(nan), 'match_day': np.float64(nan), 'match_month': np.float64(nan), 'match_year': np.float64(nan), 'start_time': np.float64(nan), 'Rank difference': np.float64(nan), 'Team value difference': np.float64(nan)}
not_related_numeric_columns :  {}

C:\Users\Abhishek k\AppData\Local\Temp\ipykernel_23432\3907210790.py:8: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  f_stats,p_value=f_oneway(Away,Draw,Home)

In [578]:
encoder = OneHotEncoder(sparse_output=False)

In [579]:
for col in categorical:
    if col!='Stage Name':
        df[col]=encoder.fit_transform(df[[col]])
df.tail()

,Team 1,Team 2,Stage Name,Group Stage,Knockout Stage,Replayed,Replay,Home Team Name,Away Team Name,Home Team FIFA Rank,...,Home_Team_Win_Pct,Away_Team_Win_Pct,Away_Team_Goals_Scored_Last5,Away_Team_Goals_Conceded_Last5,match_day,match_month,match_year,start_time,Rank difference,Team value difference
959,0.0,0.0,quarter-finals,0,1,0,0,0.0,0.0,5.0,...,45.21,55.71,13,6,10,12,2022,22.0,2.0,-70.0
960,0.0,0.0,semi-finals,0,1,0,0,0.0,0.0,2.0,...,59.30,57.14,6,3,13,12,2022,22.0,-5.0,595.0
961,0.0,0.0,semi-finals,0,1,0,0,0.0,0.0,3.0,...,56.34,28.57,5,1,14,12,2022,22.0,-8.0,850.0
962,0.0,0.0,third-place match,0,1,0,0,0.0,0.0,7.0,...,55.17,27.27,5,3,17,12,2022,18.0,-4.0,15.0
963,0.0,0.0,final,0,1,0,0,0.0,0.0,2.0,...,59.77,56.94,9,4,18,12,2022,18.0,-1.0,-240.0

In [580]:
df["Stage Name"].unique()

array(['group stage', 'semi-finals', 'final', 'round of 16',
       'quarter-finals', 'third-place match', 'final round',
       'second group stage'], dtype=object)

In [581]:
df["Stage Name"]=df["Stage Name"].map({"group stage":0,"second group stage":0, "round of 32":1, "round of 16":2, "quarter-finals":3, "semi-finals":4,"third-place match":4, "final round":5,"final":5})
df.tail()

,Team 1,Team 2,Stage Name,Group Stage,Knockout Stage,Replayed,Replay,Home Team Name,Away Team Name,Home Team FIFA Rank,...,Home_Team_Win_Pct,Away_Team_Win_Pct,Away_Team_Goals_Scored_Last5,Away_Team_Goals_Conceded_Last5,match_day,match_month,match_year,start_time,Rank difference,Team value difference
959,0.0,0.0,3,0,1,0,0,0.0,0.0,5.0,...,45.21,55.71,13,6,10,12,2022,22.0,2.0,-70.0
960,0.0,0.0,4,0,1,0,0,0.0,0.0,2.0,...,59.30,57.14,6,3,13,12,2022,22.0,-5.0,595.0
961,0.0,0.0,4,0,1,0,0,0.0,0.0,3.0,...,56.34,28.57,5,1,14,12,2022,22.0,-8.0,850.0
962,0.0,0.0,4,0,1,0,0,0.0,0.0,7.0,...,55.17,27.27,5,3,17,12,2022,18.0,-4.0,15.0
963,0.0,0.0,5,0,1,0,0,0.0,0.0,2.0,...,59.77,56.94,9,4,18,12,2022,18.0,-1.0,-240.0

In [582]:
label_encoder=LabelEncoder()
y["Result"]=label_encoder.fit_transform(y["Result"])
y

C:\Users\Abhishek k\AppData\Local\Temp\ipykernel_23432\1829080995.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y["Result"]=label_encoder.fit_transform(y["Result"])

     Result
0         2
1         2
2         2
3         2
4         2
..      ...
959       0
960       2
961       2
962       2
963       2

[964 rows x 1 columns]

In [583]:
#columns_to_encode = [col for col in x.columns if x[col].dtype == "object"]
#for col in columns_to_encode:
#    x[col] = label_encoder.fit_transform(x[col])
#y["Result"]=label_encoder.fit_transform(y["Result"])
#x.tail()

In [584]:
x_train,x_test,y_train,y_test=train_test_split(df,y,test_size=0.2,random_state=42,stratify=y)

In [585]:
y["Result"].unique()

array([2, 1, 0])

In [586]:
#smote=SMOTE(random_state=42)
##y_train_single = y_train.idxmax(axis=1)
#x_trains, y_trains = smote.fit_resample(x_train, y_train_single)
#y_trains = pd.DataFrame(y_trains, columns=y_train.columns)

In [587]:
parms={
    "objective":"binary:logistics",
    "max_depth":4,
    "learning_rate":0.1,
    "n_estimators":100,
    "alpha":0.5
}
#xgb = XGBClassifier(
#    objective="multi:softmax",
#    num_class=3,
#    max_depth=6,
#    learning_rate=0.05,
#    n_estimators=300,
#    subsample=0.8,
#    colsample_bytree=0.8,
#    random_state=42
#)
xgmodel=XGBClassifier(**parms)
bagging=BaggingClassifier(xgmodel,n_estimators=10,random_state=42)
xgmodel.fit(x_train,y_train)
y_pred=xgmodel.predict(x_test)
print(classification_report(y_test,y_pred)) 
print(confusion_matrix(y_test,y_pred))
#bagging.fit(x_train,y_train)
#y_pred_bagging=bagging.predict(x_test)
#print(classification_report(y_test,y_pred_bagging))
#print(confusion_matrix(y_test,y_pred_bagging))

              precision    recall  f1-score   support

           0       0.62      0.62      0.62        48
           1       0.25      0.08      0.12        36
           2       0.74      0.90      0.81       109

    accuracy                           0.68       193
   macro avg       0.54      0.54      0.52       193
weighted avg       0.62      0.68      0.64       193

[[30  6 12]
 [10  3 23]
 [ 8  3 98]]